Project Structure: {
  Header -- App
  Footer -- App
  CreatePollForm -- App
  PollList -- App
  Store -- CreatePollForm: {
    style: {
      stroke-dash: 3
    }
  }
  Store -- PollList: {
    style: {
      stroke-dash: 3
    }
  }
  PollList -- PollDetails
Reusable Components {
  Button
  Card
  Tabs
}
}
